INSERT INTO category (category_id, name) VALUES (1, 'American');
INSERT INTO category (category_id, name) VALUES (2, 'Italian');
INSERT INTO category (category_id, name) VALUES (3, 'Mexican');
INSERT INTO category (category_id, name) VALUES (4, 'Fast Food');
INSERT INTO unit_of_measure (id, unit) VALUES (1, 'Teaspoon');
INSERT INTO unit_of_measure (id, unit) VALUES (2, 'Tablespoon');
INSERT INTO unit_of_measure (id, unit) VALUES (3, 'Cup');
INSERT INTO unit_of_measure (id, unit) VALUES (4, 'Pinch');
INSERT INTO unit_of_measure (id, unit) VALUES (5, 'Ounce');
INSERT INTO unit_of_measure (id, unit) VALUES (6, 'Each');
INSERT INTO unit_of_measure (id, unit) VALUES (7, 'Dash');
INSERT INTO unit_of_measure (id, unit) VALUES (8, 'Pint');